---
security:
  basic:
    enabled: true
  user:
    name: test
    password: test
server:
  port: 8080
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/vivesh06/cloud-config
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - '*/perf'
              uri: https://github.com/vivesh06/cloud-config-pref
              search-paths:
                - 'station*'
          #username: 
          #password: 